/** @type {import('tailwindcss').Config} */
export default {
  darkMode: ["class"],
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        easydo: {
          bg: "hsl(var(--easydo-bg))",
          bgSoft: "hsl(var(--easydo-bg-soft))",
          surface: "hsl(var(--easydo-surface))",
          surfaceWarm: "hsl(var(--easydo-surface-warm))",
          surfaceHover: "hsl(var(--easydo-surface-hover))",
          surfaceActive: "hsl(var(--easydo-surface-active))",
          cream: "hsl(var(--easydo-cream))",
          text: "hsl(var(--easydo-text))",
          textSecondary: "hsl(var(--easydo-text-secondary))",
          textMuted: "hsl(var(--easydo-text-muted))",
          textDisabled: "hsl(var(--easydo-text-disabled))",
          gold: "hsl(var(--easydo-gold))",
          goldHover: "hsl(var(--easydo-gold-hover))",
          goldActive: "hsl(var(--easydo-gold-active))",
          goldSoft: "hsl(var(--easydo-gold-soft))",
          lavender: "hsl(var(--easydo-lavender))",
          lavenderSoft: "hsl(var(--easydo-lavender-soft))",
          lavenderSurface: "hsl(var(--easydo-lavender-surface))",
          violet: "hsl(var(--easydo-violet))",
          border: "hsl(var(--easydo-border))",
          borderSoft: "hsl(var(--easydo-border-soft))",
          borderLavender: "hsl(var(--easydo-border-lavender))",
          success: "hsl(var(--easydo-success))",
          warning: "hsl(var(--easydo-warning))",
          danger: "hsl(var(--easydo-danger))",
          info: "hsl(var(--easydo-info))",
        },
        border: "hsl(var(--border))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        muted: "hsl(var(--muted))",
        "muted-foreground": "hsl(var(--muted-foreground))",
        card: "hsl(var(--card))",
        "card-foreground": "hsl(var(--card-foreground))",
        popover: "hsl(var(--popover))",
        "popover-foreground": "hsl(var(--popover-foreground))",
        primary: "hsl(var(--primary))",
        "primary-foreground": "hsl(var(--primary-foreground))",
        secondary: "hsl(var(--secondary))",
        "secondary-foreground": "hsl(var(--secondary-foreground))",
        accent: "hsl(var(--accent))",
        "accent-foreground": "hsl(var(--accent-foreground))",
        destructive: "hsl(var(--destructive))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        sidebar: "hsl(var(--sidebar))",
        "sidebar-foreground": "hsl(var(--sidebar-foreground))",
        "sidebar-primary": "hsl(var(--sidebar-primary))",
        "sidebar-primary-foreground": "hsl(var(--sidebar-primary-foreground))",
        "sidebar-accent": "hsl(var(--sidebar-accent))",
        "sidebar-accent-foreground": "hsl(var(--sidebar-accent-foreground))",
        "sidebar-border": "hsl(var(--sidebar-border))",
        "sidebar-ring": "hsl(var(--sidebar-ring))",
      },
      fontFamily: {
        sans: ["var(--font-sans)", "ui-sans-serif", "system-ui", "sans-serif"],
        heading: ["var(--font-heading)", "var(--font-sans)", "ui-sans-serif", "system-ui", "sans-serif"],
      },
      borderRadius: {
        easydo: "18px",
        "easydo-lg": "24px",
        "easydo-xl": "32px",
        lg: "var(--radius)",
        md: "calc(var(--radius) - 4px)",
        sm: "calc(var(--radius) - 8px)",
      },
      boxShadow: {
        "easydo-card": "var(--easydo-shadow-card)",
        "easydo-glow": "var(--easydo-shadow-glow)",
        "easydo-lavender": "var(--easydo-shadow-lavender)",
      },
    },
  },
  plugins: [],
};
